### ISSUE TITLE
Android Porting?

### ISSUE THREAD

**Issue by deep-gaurav** [huxingyi/dust3d#10]
Hi,

I'd been following Dust 3D for a while it's a great software,. 
I was going through your post of readthedoc since it only has CGAL and QT5 as dependency, and both support android, do you think porting it to android is possible? There is no serious modelling tool available to date and mobile is becoming more popular for productivity day by day, it may prove useful.
 
Edit: Not suggesting it as issue, or a priority, but I can try to port it if it interests?

**Comment by huxingyi** [comment]
Hi, thanks for your suggestion,
You are right, the main dependences are CGAL, Qt5, and meshlite which written in rust language. I guess rust can also run on Android.
If you can port Dust3D to mobile platform, that would be very grateful.

**Comment by deep-gaurav** [comment]
That's great, I'll try to work on it in a few days,

**Comment by huxingyi** [comment]
Hi, I am closing this now for the coming 1.0 version. Please feel free to open a new issue for the latest version.
