### ISSUE TITLE
Add UI scaling

### ISSUE THREAD

**Issue by jbatistareis** [huxingyi/dust3d#101]
My notebook have a 15.6" screen with a resolution of 1920x1080, because of that i need to set Windows screen scaling to 115% to be able to see properly.
It would be nice if Dust3D scaled its UI following the OS value, or by an adjustable fixed value, because its icons are too hard to see at my screen, and it can be even more problematic for people with smaller screens.

Look at the size difference between the application icons, and the notification area icons:
![Clipboard02](https://user-images.githubusercontent.com/9679303/107549903-47f80580-6bc8-11eb-87c0-c5f7d28dc191.jpg)

**Comment by darthbator** [comment]
I'll second this. It's almost impossible for me to select part tools on my 1080p monitor. I just came back hoping this might be addressed in the first RC but it still seems to be a pretty serious issue that stops me from using or recommending the app.

**Comment by anthonyfinch** [comment]
As a heads up, QT respects an environment variable called QT_SCALE_FACTOR, (on linux at least) so I run it like so: 

QT_SCALE_FACTOR=2 ~/downloads/dust3d-1.0.0-rc.6.AppImage

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
