### ISSUE TITLE
architecture

### ISSUE THREAD

**Issue by clc04** [huxingyi/dust3d#104]
How to support arm64, mips architecture

**Comment by clc04** [comment]
/home/uos/Desktop/clc/dust3d/thirdparty/instant-meshes/instant-meshes-dust3d/ext/tbb/src/tbb/tools_api/ittnotify_config.h:329:11: error: ?__TBB_machine_fetchadd4? was not declared in this scope
    return __TBB_machine_fetchadd4(ptr, 1) + 1L;
           ^~~~~~~~~~~~~~~~~~~~~~~
/home/uos/Desktop/clc/dust3d/thirdparty/instant-meshes/instant-meshes-dust3d/ext/tbb/src/tbb/tools_api/ittnotify_config.h:329:11: note: suggested alternative: ?__atomic_fetch_add_4?
    return __TBB_machine_fetchadd4(ptr, 1) + 1L;
           ^~~~~~~~~~~~~~~~~~~~~~~
           __atomic_fetch_add_4

**Comment by huxingyi** [comment]
There is an old version which could be compiled on Raspberry Pi, I guess is the same architecture, please check #53 for reference.

**Comment by clc04** [comment]
The old version can be compiled on arm64 and MIPS64 without relying on TBB library, while the new version can only be compiled on X86

**Comment by huxingyi** [comment]
The TBB library may be removed from the next version.

**Comment by luzpaz** [comment]
Can this ticket be renamed to reflect what it's requesting ?

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
