### ISSUE TITLE
Is it working on Mac?

### ISSUE THREAD

**Issue by enzyme69** [huxingyi/dust3d#11]
I am using Mac, is this Dust 3D app working on Mac, or just Windows only?

**Comment by huxingyi** [comment]
It works on Mac, Windows and Linux.

Here is the direct download link for Mac: https://github.com/huxingyi/dust3d/releases/download/unstable/dust3d_unstable.dmg

Other system please refer to https://dust3d.readthedocs.io/en/latest/install.html

**Comment by huxingyi** [comment]
Wow, you are Jimmy Gunawan, incredible! I was heavily inspired by your blog post when I start write this app.

**Comment by huxingyi** [comment]
Hi, I am closing this now for the coming 1.0 version. Please feel free to open a new issue for the latest version.
