### ISSUE TITLE
Ellipsoids at nodes?

### ISSUE THREAD

**Issue by shankarsivarajan** [huxingyi/dust3d#115]
Is there a way to create ellipsoids at the nodes instead of spheres, perhaps by editing the .ds3 file directly? There doesn't seem to be a way to do this through the GUI.

**Comment by smitherik** [comment]
I believe you could accomplish this with the thickness and width sliders within the GUI.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
