### ISSUE TITLE
Zoom in pose screen

### ISSUE THREAD

**Issue by kidandcat** [huxingyi/dust3d#120]
It would be great to be able to zoom in the pose screen, if I use not big bones, it's almost imposible to click the right bone nodes, as they are too small.

(if pose nodes should be already zoomable, it doesn't work in macos)

**Comment by huxingyi** [comment]
Thanks for the suggestion, pose editor is been removed from next release. Motion will become more generative than manual editing.

**Comment by kidandcat** [comment]
Awesome!! I recently found Dust3D, and I found it to be a very useful tool. Learning it now. Soon I want to start publishing my models to the community!

Thanks for your work!
