### ISSUE TITLE
Suddenly app not responding

### ISSUE THREAD

**Issue by MikelFuentes** [huxingyi/dust3d#123]
After some uses the app won't open and even though I have deleted and copied again the files. The app window opens but there is only a white screen and despite waiting nearly 30 mins it won't change and says app not responding. Any idea of why could it be? do you need a log or something?

**Comment by huxingyi** [comment]
Asuming you are using Windows, try remove all *.d3b files in C:\Users\<Your username>\AppData\Roaming\Dust3D\Dust3D

I guess there maybe a corrupted autosaved project file failed on open.

**Comment by MikelFuentes** [comment]
That directory was empty I have deleted the folders just in case and still nothing.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
