### ISSUE TITLE
A short-lived hope...

### ISSUE THREAD

**Issue by Gilbert1915** [huxingyi/dust3d#124]
Hi Jeremy,
as I first met Dust3D (about half an hour ago) I couldn't believe my eyes: in a 3Dworld where hardware and software are glibly overloaded with zillions of useless vertices and surfaces, a piece of software dedicated to creating _good_ low-poly models is really a rare pearl.

Unfortunately though I'm tied to my good old (ancient?) Win XP - mostly but not only because I like to stay master and commander on my own ship - and as such I found out all too soon that even the 32-bit version of Dust3D won't run on it - despite Dust3D's "multiplatformity". 

Do you see any way I could escape this impasse without having to downgrade to a new but not necessarily better Windows version?

Thanks!

Gilbert

**Comment by huxingyi** [comment]
Most likely, next version of Dust3D will get rid of Qt, and based on Google ANGLE. I am not sure if Google ANGLE can support Windows XP or not. If you want to follow the latest development of Dust3D, I am updating the experiment code here: https://github.com/huxingyi/tubetube, it will be applied to this repo later when it get matured. Thanks.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
