### ISSUE TITLE
Mirror won't work

### ISSUE THREAD

**Issue by Dartsgame974** [huxingyi/dust3d#125]
Hi, I'm trying to use the mirror but nothing happens!

![image](https://user-images.githubusercontent.com/80755313/171250234-fcf1ba21-18cb-4f61-9dde-f2ab540732ca.png)

![image](https://user-images.githubusercontent.com/80755313/171250450-bde70c19-0f9f-43e0-9da6-d25f1354dfcb.png)
Can u help me

**Comment by Dartsgame974** [comment]
I admit that you had lost me O_O

**Comment by Dartsgame974** [comment]
Thanx

**Comment by Dartsgame974** [comment]
Its good! Do you a discord seerveer?

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
