### ISSUE TITLE
Add native Wayland support

### ISSUE THREAD

**Issue by kreaninw** [huxingyi/dust3d#135]
I try to launch Dust3D with `QT_QPA_PLATFORM=wayland ./dust3d-1.0.0-rc.6.AppImage`. This is the return I am getting in the terminal:

```
$ QT_QPA_PLATFORM=wayland ./dust3d-1.0.0-rc.6.AppImage
This application failed to start because it could not find or load the Qt platform plugin "wayland" in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

Without native Wayland support, the app UI is very blurry.

About info:

```
Dust3D 1.0.0-rc.6 (version: 1.0.0.36 build: Apr 12 2020 11:22:47)
opengl: 4.6 (Core Profile) Mesa 22.1.7 shader: 4.60 core: true
```

I am running the app on openSUSE Tumbleweed.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
