### ISSUE TITLE
GNU/Linux build fails miserably

### ISSUE THREAD

**Issue by jtsiomb** [huxingyi/dust3d#14]
Trying to build on GNU/Linux and it fails to find meshlite.h. Running a find I can only locate a file by that name in a directory called meshlite_unstable_vc14... which contains a precompiled library for windows! Where is the code for meshlite? and why don't you include the code for that, so it can be built on all systems instead of precompiled binaries?

If that library is not free software, and it's not an optional dependency, then your modeller is not really free software either. Please either replace it, make it optional, or provide the source code.

**Comment by huxingyi** [comment]
Hi, thanks for your interest. The precompiled library is only for windows.
The meshlite is a separate library which also written by me and it's of course open-sourced and licensed on the same MIT license. You can find it here: https://github.com/huxingyi/meshlite

About the building process of meshlite on linux, please refer to the specified section of travis file https://github.com/huxingyi/dust3d/blob/master/.travis.yml#L63
Also the build docs: http://docs.dust3d.org/en/latest/builds.html

And if you just want the binary for linux, please download the https://github.com/huxingyi/dust3d/releases/download/unstable/dust3d_unstable-x86_64.AppImage
(Only tested on ubuntu currently)

More info about AppImage:
https://appimage.github.io/Dust3D/
https://appimage.org/

**Comment by jtsiomb** [comment]
Thanks, I managed to build it. May I suggest adding build instructions on the readme file? Also libmeshlite needs to be installed to /usr/local/lib in for the dynamic loader to be able to find it. I copied it manually and ran ldconfig, but it's best if there's a documented way to install it, part of the build system itself. Usually this is achieved with `make install`, but I haven't got a clue what crate is and if it has something equivalent. Again, documenting all that in the appropriate readme file would be most helpful.

**Comment by huxingyi** [comment]
Hi, you are right, the build section is lack in the README file currently.
To keep the README file as artist friendly as possible, adding a BUILD file and provide a link to [docs/builds.rst](https://github.com/huxingyi/dust3d/blob/master/docs/builds.rst) inside could be a better choice, I guess.
Recently, I am working on other features of this software. If you have time and interest to purify the documentation of [docs/builds.rst](https://github.com/huxingyi/dust3d/blob/master/docs/builds.rst), also the [project file](https://github.com/huxingyi/dust3d/blob/master/dust3d.pro) that would be very appreciated.

**Comment by ScorrMorr** [comment]
@huxingyi dust3d looks very interesting to me, thank you.

I also think making the build process as effortless as possible is important to attract developers to contribute to this project. I wanted to give it a quick try (from a developers point of view, not an artist), but after first not even finding the build instructions and then seeing how complicated they are, i decided to use my Saturday afternoon for something else. So if you have the time to work in this it would be cool:D

**Comment by huxingyi** [comment]
@ScorrMorr Hi, thanks for your interest. You are right, I will try to improve the build instructions and make the repo home page more developer friendly. It was made artist friendly because there is nowhere to demo the software, now, there is a homepage https://dust3d.org for artist.
