### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by NedFlanders2** [huxingyi/dust3d#140]
Hello, just wondering a few things.

1. How come some features have been removed? like the rigging and some of the other features like menus and other tools?
2. What happened to the website? it gone very bare bones
3. is there a Discord?

**Comment by huxingyi** [comment]
1. Hi, the features which are not mature enough are been removed.
2. The website has been remade to keep only minimal useful information, and decrease the maintaining efforts.
3. No.

**Comment by huxingyi** [comment]
It's possible, but maybe in another app. This app(Dust3D) will focus on modelling and texturing from now on.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
