### ISSUE TITLE
Add to requirements gcc-4.9 or fix error

### ISSUE THREAD

**Issue by PowPingDone** [huxingyi/dust3d#16]
When compiling dust3d I was greeted with this glorious error: 
```src/meshgenerator.cpp: In member function ‘bool MeshGenerator::checkIsComponentDirty(QString)’:
src/meshgenerator.cpp:396:20: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]
             return nullptr;
```

Here is the [compile log](https://gist.github.com/PowPingDone/23e6e6d4e1368da02689392e49003022)

I did a quick search and this was a set feature from gcc <5. I was using gcc 8.2.3 to compile. 

Either fix the error or add to the requirements that you need gcc-4.9.

**Comment by PowPingDone** [comment]
``return isDirty;`` works, it compiles fine. I have another problem though, dust3d segfaults when creating a node now.

**Comment by huxingyi** [comment]
Could you paste the stack trace here please, maybe is the same crash as https://github.com/huxingyi/dust3d/issues/15 ?

**Comment by huxingyi** [comment]
Thanks for the dump, it crash on the same place as #15 
I guess it's something related with the OpenGL offline render, but I couldn't figure out yet.
Could you make a pull request regarding the compile error please? 
Never mind the crash, I am going the change this part after your pull request, by avoiding OpenGL offline render feature.

**Comment by huxingyi** [comment]
Thanks for your PR, and I will try to fix the crash, once it's done I will let you known by ping you in this issue.

**Comment by huxingyi** [comment]
Hi, @PowPingDone  Could you help to verify if the latest build (master branch) still crash when you add the first node please? Thanks in advance.

**Comment by PowPingDone** [comment]
@huxingyi It has been fixed. Thank you.
