### ISSUE TITLE
High DPI Scaling

### ISSUE THREAD

**Issue by deckar01** [huxingyi/dust3d#19]
**Problem**

The text is difficult to read in the UI on high DPI displays.

**Repro**

1. Set the DPI scaling of your operating system to 100%
2. Observe the text size of Dust3D
3. Set the DPI scaling of your operating system to 150% or 200%
2. Observe the text size of Dust3D

**Expectation**

I expected the text size of Dust3D to scale with the operating system's DPI.

**Actual**

The text size of Dust3D remains relative to the resolution of the display.

**Related**

- #1

**References**

- http://doc.qt.io/qt-5/highdpi.html#migration-of-existing-applications

**Comment by deckar01** [comment]
The QT docs mention that DPI scaling is handled differently on MacOS, so I'm not sure if this is just an issue on Windows. I will try to repro on a retina display.

**Comment by bmv437** [comment]
I have a Huawei Matebook X Pro running ubuntu, which has a high DPI display, and I'm running into the same issue. The UI is extremely small. Here's a screenshot:

![dust3d-high-dpi-issue](https://user-images.githubusercontent.com/1403707/49330517-e8b8f800-f55d-11e8-88b2-5f995e1e3e34.png)

**Comment by huxingyi** [comment]
Hi, thanks for reporting. I was intentionally make the font size small to enlarge the workspace. I just tried adjusting the DPI Scaling on my mac, it looks good to me. And I also think the screenshot of @bmv437 is acceptable.
However, this is just my taste, maybe change in the future if too many people have problem with it.

**Comment by iKlsR** [comment]
You really don't need to do that. Leave it at the OS defaults and or add easily toggleable widget visibility. It's your project but making assumptions like that are a sure way to make your stuff unuseable.

On my 4k display, I can barely make out the file menu and the UI is already very minimal. Saving a couple pixels are trivial compared to having people open your app and close it.

**Comment by huxingyi** [comment]
Ok, maybe I really have a small screen and cannot feel the pain as you guys.
I will make the font default size.

**Comment by mikeruddy** [comment]
Can confirm this is an issue on Win 10 if you're using scaling settings.

**Comment by huxingyi** [comment]
Thanks, I have released the 1.0.0-beta.6 which include the font fix. Could you help to verify if the default font size looks ok on large screen please?
Download links:  
[for Windows](https://github.com/huxingyi/dust3d/releases/download/1.0.0-beta.6/dust3d-1.0.0-beta.6-x86.zip)  
[for MacOS](https://github.com/huxingyi/dust3d/releases/download/1.0.0-beta.6/dust3d-1.0.0-beta.6.dmg)  
[for Linux](https://github.com/huxingyi/dust3d/releases/download/1.0.0-beta.6/dust3d-1.0.0-beta.6-x86_64.AppImage)

**Comment by huxingyi** [comment]
@mikeruddy Thanks, looks like the default font is too large on your system. I will try another method and let you know when it's been released.

> https://vr.google.com/blocks/   

This looks very interesting, thank you, I will dig into it and see what Dust3D can benefit from it.

**Comment by huxingyi** [comment]
@mikeruddy Thanks, I got you, I will think how to fit the left tool bar button size.

**Comment by huxingyi** [comment]
Hi, I just released the [1.0.0-beta.10](https://github.com/huxingyi/dust3d/releases/tag/1.0.0-beta.10) which include all the fix about fonts, could you help to verify if it looks good on high dpi screen please?

**Comment by mikeruddy** [comment]
Lookin good!

![dust3d](https://user-images.githubusercontent.com/11842589/49384298-b556a480-f6e8-11e8-903a-97018a021453.png)

**Comment by huxingyi** [comment]
Thanks!
