### ISSUE TITLE
Document minimum Mac OS version required

### ISSUE THREAD

**Issue by follower** [huxingyi/dust3d#21]
It would be helpful to document the minimum version(s) of Mac OS X / macOS that are supported by the binaries/source.

It seems that for v1.0.0-beta.6 binaries the minimum Mac OS X version is 10.10 (which I guess is driven by the use of Qt 5.9).

[Unrelated: This is a really nice overview of the evolution of the project and your process/learning: <http://docs.dust3d.org/en/latest/origin_and_future.html>. I think write-ups like that are super-valuable & educational in making people aware that projects don't just emerge fully formed. Nice work. :) ]

**Comment by huxingyi** [comment]
You are right, besides, there is also a minimum version requirement of linux because of using AppImage. Currently, the document is very basic and outdated, don't get a hand to improve it yet.

> Unrelated...   

Thanks for your kind words, what you say is the things keep me motivated.

**Comment by follower** [comment]
> Thanks for your kind words, what you say is the things keep me motivated.

Great! I can identify with that feeling. :)

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
