### ISSUE TITLE
Can't load Reference Sheet

### ISSUE THREAD

**Issue by Helspank** [huxingyi/dust3d#22]
**Problem**
Nothing happens when I try to load an image to be used as reference sheet. The program works but the canvas stays blank. No errors, alerts or dialogs of any kind.

**Steps followed**

1. Open the program.
2. File -> Change Reference Sheet...
3. Select any JPEG image file of any size or type. I also tried the ones from the modeling examples like the ant and the horse.
4. Canvas stays blank.

**System description**
Dust3D 1.0.0-beta.6, Windows 10, NVidia GTX1060, 16 GB Ram

**Comment by huxingyi** [comment]
Hi, thanks for reporting, could you help to take a screenshot of the ant example loaded please?
I guess is the qt plugin for images missing, I will add it and let you know once release ready.

**Comment by Helspank** [comment]
Hi, a screenshot would just show a blank canvas, I made a short video capture that shows exactly what I did what happens. Hope this helps!

**Comment by huxingyi** [comment]
It's not lack qt plugin problem as I thought. I just checked the Qt document,
> The core Qt Gui library by default supports reading and writing image files of the most common file formats: PNG, JPEG, BMP, GIF and a few more, ref.   
http://doc.qt.io/qt-5/qtimageformats-index.html

So, default should be no problem with png and jpeg file.

**Comment by Helspank** [comment]
Oops, I think the upload failed.

https://my.mixtape.moe/avjnti.webm

**Comment by huxingyi** [comment]
I guess you have no problem with png(Because all image files saved in the .ds3 file will be kept in png format), but jpeg not work.
Could you try the following png please? It's the same ant reference sheet but with png format.

![ant-reference-from-antweb-org](https://user-images.githubusercontent.com/3941597/49336074-b7febe80-f642-11e8-9552-b60815f3c31b.png)

**Comment by Helspank** [comment]
Yes, that worked. 
I also tried another png file and it works as well, but the same file converted in jpg doesn't.

**Comment by huxingyi** [comment]
Thanks, I guess the the qjpeg plugin is missing, I will add it and build a new release and let you know once done.

**Comment by Helspank** [comment]
Great, thanks!

**Comment by huxingyi** [comment]
Hi, I have build a new version, you should see the version in the title bar as 1.0.0-beta.7
[dust3d-unstable-x86.zip](https://github.com/huxingyi/dust3d/releases/download/unstable/dust3d-unstable-x86.zip)  
Could you try if it fixed you problem please?

**Comment by Helspank** [comment]
Tried, it works now, I tried several jpg files, including the ant one, and all have been loaded correctly.

**Comment by huxingyi** [comment]
Thank you very much.
