### ISSUE TITLE
GLX Crash on Fedora 29

### ISSUE THREAD

**Issue by Demorde** [huxingyi/dust3d#23]
Fedora 29 x64 (4.19.4), Lenovo Thinkpad x240 - i5-4300U/8GB/Intel4400

>  ./dust3d-1.0.0-beta.6-x86_64.AppImage 
> No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
> Falling back to using screens root_visual.
> Could not initialize GLX
> Aborted (core dumped)

**Comment by huxingyi** [comment]
Thanks for reporting, maybe the AppImage issue: https://github.com/probonopd/linuxdeployqt/issues/331

Let's see how it getting fixed.

**Comment by huxingyi** [comment]
Hi, could you test if this is been fixed please? remove the ".txt" (github doesn't allow upload AppImage file in comments)
[dust3d-unstable-x86_64.AppImage.txt](https://github.com/huxingyi/dust3d/files/2643884/dust3d-unstable-x86_64.AppImage.txt)

**Comment by Demorde** [comment]
That fixed it, thank you so much! It appear to work perfectly now. :)

**Comment by huxingyi** [comment]
Thanks, I have released the 1.0.0-beta.11 which includes the fix.
