### ISSUE TITLE
dust3d: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers

### ISSUE THREAD

**Issue by vanous** [huxingyi/dust3d#24]
seems related to: https://github.com/maxrd2/subtitlecomposer/issues/117
which says:
Solution: Please do not bundle

    'libxcb-dri3.so.0'
    'libxcb-dri2.so.0'

**Comment by vanous** [comment]
I can also confirm that running
chmod +x dust3d-1.0.0-beta.7-x86_64.AppImage
./dust3d-1.0.0-beta.7-x86_64.AppImage --appimage-extract
./squashfs-root/usr/bin/dust3d

works and app is running.
Awesome job btw! :)

**Comment by huxingyi** [comment]
Thanks for reporting, will fix it later.

**Comment by huxingyi** [comment]
Hi, could you test if this is been fixed please? remove the ".txt" (github doesn't allow upload AppImage file in comments)
[dust3d-unstable-x86_64.AppImage.txt](https://github.com/huxingyi/dust3d/files/2643884/dust3d-unstable-x86_64.AppImage.txt)

**Comment by huxingyi** [comment]
Thanks, the changes will be available in 1.0.0-beta.11
