### ISSUE TITLE
The following parts couldn't cut off the mesh

### ISSUE THREAD

**Issue by Toshiwoz** [huxingyi/dust3d#28]
![image](https://user-images.githubusercontent.com/21297356/51414682-48d12100-1b41-11e9-9be4-142a76b698c6.png)

Hey, as you can see from the image I'm trying to make a velociraptor, with animations and all.
But as I mark parts as limbs, I start getting problems, I'm quite sure that there's some rule I'm not aware of and that I'm not following, could be I have to orient it in a specific way?

And if I go to the poses window I get this:
![image](https://user-images.githubusercontent.com/21297356/51414744-76b66580-1b41-11e9-8380-0c1e6392c59c.png)
As you can see there's only one leg displayed, no arms either.

**Comment by Toshiwoz** [comment]
This might be useful if debugging is needed.
[dino-sauro.zip](https://github.com/huxingyi/dust3d/files/2774644/dino-sauro.zip)
And here some information about the version:
Dust3D 1.0.0-beta.14 (version: 1.0.0.14 build: Jan  7 2019 13:39:45)
opengl: 4.4.0 - Build 20.19.15.5058 shader: 4.40 - Build 20.19.15.5058 core: false

**Comment by huxingyi** [comment]
Hey, your model looks good! I adjust a little bit of the mark nodes and hands, and made two poses, one motion use these two poses, as attached:
[dino-sauro-rig.ds3.zip](https://github.com/huxingyi/dust3d/files/2774764/dino-sauro-rig.ds3.zip)
From your provided model, I can see you already got the idea how the rig and animation works.
Basically, the rigging process can be conclude as the following steps:
1. Cut off all the limbs(leg is also limb), neck, and tail as separate bone link.
2. Make a spine from the remaining main body(after all limbs and neck, tail been cut)
3. Find joints in all the bone link.
4. Connect bone link to spine to finalize the skeleton

> The following parts couldn't cut off the mesh  

This means, the first step failed. You can adjust the model, make the limb more stretched, so the generated mesh of the marked node will not touch the other parts of the body.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
