### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AnosAhmad** [huxingyi/dust3d#29]
Hello Developer, 

My name is Enas and I am a Ph.D. student. My research focuses on static code analysis. I was looking for open-source software to collect some static code analysis tool warnings. I checked your source code, and I ran one of static code analysis tools over the source code. A number of warnings were generated; some of them may represent true defects in the source code and some may represent false reports, where the tool shows a defect but in reality there is none. 

I need your help by going through the warnings and checking if any of them represent a true defect in your source code. To do that, kindly find the attached file, which contains the warnings. 

Your response and help are highly appreciated. 

Thanks, 
Enas 
 
[warnings.xlsx](https://github.com/huxingyi/dust3d/files/2873648/warnings.xlsx)

**Comment by huxingyi** [comment]
Hi, thanks for reporting, your tool looks promising. The warnings your tool generated, are definitely potential problems, however, I checked them manually, they should not be true defect.

**Comment by AnosAhmad** [comment]
Hi, thank you for telling me that. I appreciate your help.
