### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [huxingyi/dust3d#30]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [Document](https://github.com/huxingyi/dust3d/blob/e2f829d3ce082a35b27d3fdae9ce340be804a25a/src/document.cpp#L20)
- [RigGenerator](https://github.com/huxingyi/dust3d/blob/4bdbdd496a52471edee6214e97a680499b85c473/src/riggenerator.cpp#L8)

**Comment by huxingyi** [comment]
Unless there is a memory issue with the current implementation or it can make the code more readable.

**Comment by elfring** [comment]
[Smart pointers](https://en.cppreference.com/w/cpp/memory/unique_ptr "Description for std::unique_ptr") can fix mentioned aspects also in affected software components here.

**Comment by huxingyi** [comment]
Considering there is no exception throw in this repo, and I don't see any benefit of change the current working code to use std::unique_ptr, so, won't fix, sorry.

**Comment by elfring** [comment]
* How do you think about the possibility for an exception like “std::bad_alloc”?
* Would you like to [reconsider the resource management in affected source files](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”") once more?

**Comment by huxingyi** [comment]
A client application has not much to do with out of memory, if it happens, that means the whole os is unusable.

**Comment by elfring** [comment]
I would appreciate safer exception handling also for this software.
