### ISSUE TITLE
Black Screen when Running AppImage

### ISSUE THREAD

**Issue by tanooki2017** [huxingyi/dust3d#31]
Hi,
I am having an issue when running the AppImage of Dust3D.  
When I open Dust3d it gives me a black screen.  I am able to see the context menus when I right click but that's about it.

My PC is running Ubuntu 18.04
It is a Fujitsu tablet PC with an Intel(R) Core(TM) M-5Y31 with 4GB of RAM

Is there anyone else who is experiencing this?

**Comment by huxingyi** [comment]
Hi, @tanooki2017  thanks for reporting, could you provider a screenshot please?

**Comment by tanooki2017** [comment]
Hi @huxingyi,

It looks like it is now working.  I had to update the Intel Linux graphics drivers since I was also experiencing issues with some games not displaying properly as well.

**Comment by huxingyi** [comment]
That's a great news, thank you for the update.

**Comment by leebc** [comment]
@tanooki2017 I'm having the same problem.  Could you tell me what driver you updated to?
