### ISSUE TITLE
there are wrongs, when calculation

### ISSUE THREAD

**Issue by KeepFenDou** [huxingyi/dust3d#32]

**Comment by KeepFenDou** [comment]
![wrong](https://user-images.githubusercontent.com/39907744/57688542-4787af00-7670-11e9-895c-7e41d21e41f1.png)

**Comment by huxingyi** [comment]
Hi, @KeepFenDou Thanks for pointing out. It's a little bit weird when the three branches come together at specified angles and radius, definitely need more work on the optimization of the generating algorithm.

**Comment by KeepFenDou** [comment]
thanks for reply, i find that older version(beta 4) can get proper result,
maybe, because you change some parameter in the new version(beta 16).

**Comment by huxingyi** [comment]
Yes, I just downloaded the beta 4, and played with some new models I made recently. The generated result is quite different, in some case, the older version is even better.
The mesh generating algorithm was been rewritten since version 1.0.0-beta.15, it was implemented in Rust language before beta 15, now it's in C++, although the language shouldn't make the result such difference, the main reason, is that the preprocess of generating and branch face stitching are different between the old and new methods.
I need to reconsider some algorithm which works better in the older version.
Thanks!

**Comment by KeepFenDou** [comment]
two point:
1.branch face stitching should consider the node connected to me first,not the nearest to me.
2.one node should consider keeping spherical first, not face stitching.

**Comment by huxingyi** [comment]
Thanks, could you elaborate point 1 please? When you say "nearest" do you mean the mesh should not combine even intersects each other? I implemented a "Uncombined mode" in the latest but not release yet version [here](https://github.com/huxingyi/dust3d/releases/tag/unstable), please ignore the date on the page, it shows the first day of the tag created.

![May-15-2019 08-03-53](https://user-images.githubusercontent.com/3941597/57736690-0f23b780-76e8-11e9-84aa-df40fb0deae4.gif)

**Comment by KeepFenDou** [comment]
no, i mean that, for example,there are three nodes connect to one line, the first node should stitch to the second node first, not the third node. even the third node is nearer.

**Comment by huxingyi** [comment]
The nodes in the straight line should stitch first, right? Em, that's a very good idea.

**Comment by KeepFenDou** [comment]
英文不太好,表达不清,直接用中文吧,
就是尽量保持由node和line组成的图形的原始形状,
这样的好处是能最大限度的遵循建模者的想法,否则就增加了塑形困难.
![pic](https://user-images.githubusercontent.com/39907744/57743822-3931a580-76f9-11e9-9375-46b8b0c9552a.png)

**Comment by huxingyi** [comment]
Thanks for the graph, I understand what you mean now.
The new stitching algorithm can handle more edge cases but the result is worse.
The smooth is come from the preprocess of adding intermediate nodes which could make the result mesh edges more even.
I am going to do some experiments based on your suggestion, and I will let you know if there is any update.

**Comment by KeepFenDou** [comment]
thanks, and thanks for your hard work.

**Comment by huxingyi** [comment]
Hi, @KeepFenDou I have changed the wrapping algorithm, what do you think? Please download the latest build from here: https://github.com/huxingyi/dust3d/releases/tag/unstable
Thanks!

**Comment by KeepFenDou** [comment]
thanks, now the result is correct.
<img width="427" alt="right" src="https://user-images.githubusercontent.com/39907744/58619159-e52ce080-82f6-11e9-8509-9ee736f46b0f.png">
