### ISSUE TITLE
Check list to release 1.0 stable

### ISSUE THREAD

**Issue by huxingyi** [huxingyi/dust3d#33]
- [ ] Fix export issues for Unreal Engine  
- [ ] Add Dust3D package importer/exporter  
- [X] Support multiple languages  
    **If your language not listed, please comment to add.**
    - [X] zh_CN
    - [ ] it_IT @MrAlexEsisteGia
    - [X] es_AR @azagaya 
    - [ ] fr_FR @Calinou
- [ ] Add detailed tutorials  
- [ ] Update documents  
- [x] Make new logo  
- [ ] Make new homepage  
- [ ] Make a demo scene in game engine using assets exported from Dust3D  

Can I contribute a translation?
============================
Yes, translator wanted! Please comment what language you want to claim, you can claim multiple languages. Once claim confirmed by me, you can start translation and make a pull request when you finished, and don't forget to add your name into [CONTRIBUTORS](https://github.com/huxingyi/dust3d/blob/master/CONTRIBUTORS) in your pull request.

How to start translation?
==================
Download [dust3d_zh_CN.ts](https://github.com/huxingyi/dust3d/blob/master/languages/dust3d_zh_CN.ts), this is simplified Chinese, replace the "zh_CN" in this line: `<TS version="2.1" language="zh_CN">` and the file name: `dust3d_zh_CN.ts` to your claimed language name.

For example, if I claimed "zh_TW", then I replace the line to: `<TS version="2.1" language="zh_TW">` and the file name change to `dust3d_zh_TW.ts`.

.ts file should remain in UTF8 encode.

**P.S. Because there will be too many changes in RC.7 version, the translation is paused, please wait RC.7 to be released.**

**Comment by MrAlexEsisteGia** [comment]
it's time to speak some pizza pasta
[dust3d_it_IT.zip](https://github.com/huxingyi/dust3d/files/4131850/dust3d_it_IT.zip)
it's not finished, once I have more time ill continue it, I put a marker with "Progress!!!!!"...

**Comment by huxingyi** [comment]
Hi @MrAlexEsisteGia Thanks, great start, looking forward to the full translation. No rush, and there are a little more items need to translate in the next release, I will let you know once the added items got merged in master branch.

**Comment by MrAlexEsisteGia** [comment]
Sure!

I have 3 things to say
My Grammarly was alerting me for some typos in the English translation
I would suggest adding a "Remove reference sheet" button and the ability to zoom in/out more

Just wanted to send some feedback

**Comment by huxingyi** [comment]
Thanks for the suggestions, I have added to my TODO list.

**Comment by Calinou** [comment]
I'd like to work on a French translation (`fr_FR`) if nobody is currently doing so.

**Comment by huxingyi** [comment]
@Calinou  Hi, I have reserved the fr_FR for you, but please start after RC.7 been released. There will be a lot of changes and it will not be released soon.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.

**Comment by anderlli0053** [comment]
@huxingyi Any news on this, since i would like to add Slovenian translation..??

**Comment by huxingyi** [comment]
Hi @anderlli0053, thanks, will add back multiple languages support soon, and will request for review.
