### ISSUE TITLE
There is no way to normalize the radius of the nodes

### ISSUE THREAD

**Issue by SatishGodaPearl** [huxingyi/dust3d#34]
As you can see from the image below, I could not find a way to normalize the radius of different connected nodes. I think it would be beneficial to have that feature (unless I am totally missing it)

![image](https://user-images.githubusercontent.com/37197216/60615354-c43b2d80-9d83-11e9-9f45-126d444eaddb.png)

Thank you,
Satish.

**Comment by SatishGodaPearl** [comment]
Nevermind. I think I figured out the way to normalize the radius.

Select all the nodes in the chain and then hold SHIFT key and change the radius at once.

**Comment by huxingyi** [comment]
SHIFT key is to scale the radius more quickly. There is no direct way to normalize the radius. However you can select all the nodes and scale down to the minimal allowed size and scale up again.
