### ISSUE TITLE
Undoing of actions made using IK mode takes too long

### ISSUE THREAD

**Issue by SatishGodaPearl** [huxingyi/dust3d#35]
When I select the tip of a chain of nodes and perform an IK operation, undoing takes forever (to go to that last position of the chain of nodes). Looks like all the intermediate states of the chain of nodes are being undone one by one. 

It would be beneficial if the undo happens in one step (take the chain of nodes to the state before the ik operation.)

**Comment by huxingyi** [comment]
Thanks, currently every trivial actions are been recorded for undo. This is a problem. Sawm suggested merge all the actions to one undo batch, I thought it's a good way to fix this, but haven't implement yet, I guess you mean the same way?

https://twitter.com/jeremyhu2016/status/1069121370255122432
<img width="617" alt="Screen Shot 2019-07-04 at 06 39 38" src="https://user-images.githubusercontent.com/3941597/60625308-90fdaa80-9e26-11e9-8921-4669856ba598.png">

**Comment by SatishGodaPearl** [comment]
Yes, I mean the same way. In Maya, all commands executed can be included inside a undo chunk, so all those actions can be undone in one step. Looking forward to the undo when it gets implemented.

Thank you,
Satish.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
