### ISSUE TITLE
Feature request : Ability to update/add material for multiple nodes at once

### ISSUE THREAD

**Issue by SatishGodaPearl** [huxingyi/dust3d#36]
It would be beneficial to have the ability to add/edit the materials for a bunch of selected nodes. Please see screenshot below for an example.

![image](https://user-images.githubusercontent.com/37197216/61159968-bfc4f200-a4b2-11e9-8660-1a972db8607e.png)

Thank you,
Satish.

**Comment by huxingyi** [comment]
Thanks, really good idea, I will add it!
