### ISSUE TITLE
Feature Request : Ability to access recently used files from the File menu

### ISSUE THREAD

**Issue by SatishGodaPearl** [huxingyi/dust3d#37]
At the moment, I need to go find older files from the file system. It will be very beneficial to add a menu in the File menu that will let us load recently used/loaded files.

Thank you,
Satish.

**Comment by huxingyi** [comment]
Thanks, this is definitely a normal function every software should have :-)
I drop a link here in case some one want make a pull request,

https://doc.qt.io/archives/qt-4.8/qt-mainwindows-recentfiles-example.html
