### ISSUE TITLE
Feature Request : Display Coordinate system icon in the viewport

### ISSUE THREAD

**Issue by SatishGodaPearl** [huxingyi/dust3d#38]
Following are examples of why a coordinate system orientation display would help with modeling.

![front_side](https://user-images.githubusercontent.com/37197216/61163172-6b753e80-a4c1-11e9-968e-5e4e5d913898.png)

Without it, lots of mental load and management on the brain ensues.

![top_side](https://user-images.githubusercontent.com/37197216/61163174-7039f280-a4c1-11e9-9e1d-19ff262ca61d.png)

Thank you,
Satish.

**Comment by huxingyi** [comment]
Yes, currently, there is no reference point for preview, introduce 3d gizmo would help, but I have no idea how to show it properly.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
