### ISSUE TITLE
Ability to export to .stl

### ISSUE THREAD

**Issue by alfredoivan** [huxingyi/dust3d#39]
Hi,
Would be great for 3d printing to have the ability to export to .stl

**Comment by huxingyi** [comment]
Hi, @alfredoivan thanks for the suggestion, usually the exported .obj should work as the same as .stl for 3D printer, as far as I know, MakerBot is ok with .obj
But if you want make a pull request about exporting to .stl file I would like to merge it.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
