### ISSUE TITLE
Using Dust3d in a laptop

### ISSUE THREAD

**Issue by glasyalabolas** [huxingyi/dust3d#4]
Hi, 

Neat little program you have here! However, a minor issue is preventing me to use it in a laptop. You see, the previewed mesh is manipulated with the middle mouse button, which laptops don't have. So, could you please provide some other means to manipulate it? Like, using the mouse with ALT, or something like that (like Blender does).

Thanks, and great job so far!

Paul

**Comment by huxingyi** [comment]
Hi, thanks for your suggestion, will add it by today or tomorrow.

**Comment by huxingyi** [comment]
Hi, glasyalabolas, your suggestion is in the https://github.com/huxingyi/dust3d/commit/d930ceec96e615dacbd44ba8faa52b8df48bc270

Free free to reopen this issue if you have further issues using Dust3D in laptop. Thanks.

**Comment by glasyalabolas** [comment]
Thanks, Hu. Will try it tonight and will report back.

Say, your program is quite amazing. I was looking to code something like
this (to be able to do the 'bulk' modeling in a quick and easy way), but
wasn't able to come up with a workable idea that fitted the task. Nodes! I
should have known better ;)

Many thanks to you. See you soon.

2018-04-23 2:09 GMT-03:00 XingYi Hu <notifications@github.com>:

**Comment by huxingyi** [comment]
Thanks, the same feeling for me for many years, and recently comes to a almost worked version. There are more dream features waiting us to develop :-)

**Comment by glasyalabolas** [comment]
The latest version works like a charm, Hu. Excellent, this tool is awesome, and is indeed a dream come true for me =)

Keep up the good work!

**Comment by huxingyi** [comment]
Thanks!

**Comment by glasyalabolas** [comment]
Ups! You forgot the zoom feature =D

May I suggest CTRL+ALT+Left click?

**Comment by huxingyi** [comment]
CTRL + ALT already used in multiple unselect. um... should combine another key.
