### ISSUE TITLE
UI scaling issue

### ISSUE THREAD

**Issue by NiallPhillips** [huxingyi/dust3d#40]
I have had issues with Dust3D UI scaling on both Windows and Linux. The screenshot below shows the parts window with the UI too small to be usable and it does not scale to fill the space when I drag the separator between 3d workspace and the side menu.

![Screenshot from 2019-07-29 14-18-25](https://user-images.githubusercontent.com/18383694/62051897-421c1880-b20c-11e9-9e71-2098e784526a.png)

This screenshot was taken from a 1440p monitor but the same issue occurs for me on 1080p monitors. I am not sure if this is a duplicate of a previous issue regarding UI sizing.

**Comment by huxingyi** [comment]
Hi, @NiallPhillips thanks for reporting, it's a know issue, my original design is to make the canvas as large as possible, so all the UI elements are tiny. Will do a UI refactor in the future once I have a clear mind about how to do it.

**Comment by mokalux** [comment]
+1 for a bigger UI please.

**Comment by panbeep** [comment]
+1 
On windows ions are also very tiny. The parts icons are also hardly visible when they are inactive. I can't distinguish what they are.

**Comment by LEEbugking** [comment]
I almost put my face on screen to distinguish those icons in parts dock.It is very necessary to make UI bigger.

**Comment by NiallPhillips** [comment]
Hi @huxingyi is this issue planned to be fixed in the 1.0 release?

**Comment by huxingyi** [comment]
@NiallPhillips I am afraid it will need move to 1.1 or 2.0, UI refactoring involves too many changes.

**Comment by NiallPhillips** [comment]
Cool no worries, loving the software otherwise!

**Comment by henrytseng** [comment]
Running on archlinux with XPS 13 with HiDPI monitor - high density monitor.

![Screenshot from 2020-07-16 10-17-27](https://user-images.githubusercontent.com/539667/87682408-ca613980-c74d-11ea-84a4-160d07d30051.png)

**Comment by huxingyi** [comment]
@henrytseng Thanks for the screenshot.

**Comment by anthonyfinch** [comment]
As a heads up, QT respects an environment variable called QT_SCALE_FACTOR, (on linux at least) so I run it like so: 

QT_SCALE_FACTOR=2 ~/downloads/dust3d-1.0.0-rc.6.AppImage

**Comment by HerculeHolmes** [comment]
I hope this issue can be overcome. I suspect that 99% of people using this program are on laptops or using standard-sized screens (as I am). It's not really possible to use the program without a very large screen.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
