### ISSUE TITLE
[BUG?] creating models, flips legs/arms

### ISSUE THREAD

**Issue by lewislepton** [huxingyi/dust3d#44]
this is something I have noticed with 2 models I was practicing with dust3d. id send the actual files, but it crashed when I was about to send this originally.

but this second time I did get a screen shot & am quite confused as to why the model has its left leg on the right hand side. its really odd. so when I then put in the right arm/leg, it will go to the left hand side

im not sure what im doing wrong since im just testing things out right away. plus looked at how you had set things up in a video

thanks

<img width="1036" alt="Screenshot 2019-08-28 at 21 49 24" src="https://user-images.githubusercontent.com/11299322/63891924-358f0980-c9de-11e9-8f63-7edf8a0063a7.png">

**Comment by huxingyi** [comment]
Thanks, where are the green nodes? Also with the crash, if you can reproduce it in a several steps, that would be grateful.

**Comment by lewislepton** [comment]
the green ones are at the side. the crashes happened when I grabbed about 3/5 nodes to move & it crashed. ill see if I can catch it again. I was hoping a report would pop up to post, but none did

**Comment by huxingyi** [comment]
Thanks, haven't added the crash report yet. May add in the future.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
