### ISSUE TITLE
Change icon name on Dust3D

### ISSUE THREAD

**Issue by creepertron95** [huxingyi/dust3d#45]
I found out that the icon name for Dust3D was called icon on the icon line of the desktop file. 
https://github.com/huxingyi/dust3d/blob/master/ci/dust3d.desktop
https://github.com/huxingyi/dust3d/blob/master/ci/icon.png

Could the icon be renamed to **dust3d** for icon themes?

**Comment by huxingyi** [comment]
Sure, I am not familiar with the icon themes requirement, could you make a pull request to rename it and make it as proper size for the icon themes please? You can download the source document of the icon from [here](https://dust3d.discourse.group/t/dust3d-media-press-kit/68), thanks!

**Comment by creepertron95** [comment]
I have created a Pull Request to rename the icon but, I wanted you to test the program for errors before you merge.

**Comment by creepertron95** [comment]
The icon themes like Numix Icon theme already has an icon with the name. 
https://github.com/numixproject/numix-core/pull/4818
I will probably create one for the papirus icon theme as well.
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

**Comment by creepertron95** [comment]
I guess the issue is fixed so I will close the issue.

**Comment by huxingyi** [comment]
@creepertron95 Thanks for your contribution. 

I don't know where to check if it works for icon themes. For example, I can't see the icon show on the file explorer:
<img width="203" alt="Screen Shot 2019-11-02 at 12 45 24" src="https://user-images.githubusercontent.com/3941597/68065315-e57e4b80-fd6e-11e9-99ed-9de2dda3f12a.png">

Could you help to check if the icon works for the icon themes please?
You can download the AppImage file from [here](https://github.com/huxingyi/dust3d/releases/download/unstable/dust3d-unstable-x86_64.AppImage), thanks!

**Comment by creepertron95** [comment]
I will create an icon for Papirus icon theme and see if it works.

**Comment by creepertron95** [comment]
I have created a Dust3D icon for the papirus-icon-theme.
You can see my commit here:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/c0cebaf4378fb5c3e2bc0d8bd33298ba788007f3

**Comment by huxingyi** [comment]
Thanks!
