### ISSUE TITLE
xdg-open: no method available

### ISSUE THREAD

**Issue by johhnry** [huxingyi/dust3d#48]
Hi there,

I am on Kali linux (`5.3.0-kali2-amd64 #1 SMP Debian`) and I am using the latest version of dust3d (`dust3d-1.0.0-beta.27-x86_64.AppImage`).

Now when I click on `Help > Dust3D Homepage`, there's an error with `xdg-open` : 

```
/usr/bin/xdg-open: 870: www-browser: not found
/usr/bin/xdg-open: 870: links2: not found
/usr/bin/xdg-open: 870: elinks: not found
/usr/bin/xdg-open: 870: links: not found
/usr/bin/xdg-open: 870: lynx: not found
/usr/bin/xdg-open: 870: w3m: not found
xdg-open: no method available for opening 'https://dust3d.org/'

```

Is it linked to my current xdg-open configuration? (It's not working with `Source Code`, `Reference Guide` and `Report Issue`)

Thanks

**Comment by huxingyi** [comment]
Thanks for reporting, looks like it's an AppImage related with xdg-open issue, if extract and run, it should work
```
$ ./dust3d-1.0.0-beta.27-x86_64.AppImage --appimage-extract
$ ./squashfs-root/AppRun
```

**Comment by johhnry** [comment]
Yes it works, thanks for your reply.
