### ISSUE TITLE
[REQUEST] make this awesome software IPAD PRO compatible

### ISSUE THREAD

**Issue by kh4o** [huxingyi/dust3d#49]
Love what you guys did. Dust3D is absolutely perfect to work from an IPAD PRO, would you consider releasing it on app store ?

**Comment by huxingyi** [comment]
Hi @kh4o thanks for the suggestion. Currently, there are some dependencies which are not iOS compatible, and in the near future, there are more dependencies would be introduced to support high poly sculpting feature and also not iOS friendly. Besides this, publish to iOS is not free, and it has a annual fee to keep the App in AppStore. 
I hope these issues can be resolved in the future.

**Comment by kh4o** [comment]
First thanks for the fast answer, it’s super kind. I would totally be ok to publish it (and pay was it’s needed) for free if that’s the main concern. Also i don’t know if it helps: the new Ipad got Ipad OS now and software like paint clip studio (that were very desktop-ish) works very well on it
.
What I understand is that even if we fix the money problem the dependencies are too much of a hassle to get an Ipad version. Well if one day you want to try this road (because even if sometimes I hate Apple, the Ipad Pro + Pencil is just too good), know that you have an audience there !

**Comment by huxingyi** [comment]
Pencil is really attractive. Will do some searching on the iPad OS. Thanks!

**Comment by bobpepin** [comment]
Very nice software indeed, and I agree that the concept would be ideally suited to touchscreens. One rather involved option to make it mobile friendly would be to swap Qt for a web interface with html5 and WebGL, keeping the computational parts in C++ and compiling to wasm. That is of course a lot of effort, on the flipside browsers tend to stay up to date with new kinds of input devices.

**Comment by huxingyi** [comment]
Yes, webassembly could be an option, but not at the moment, maybe after 1.0 stable version been released.

**Comment by huxingyi** [comment]
Experiment WebAssembly Version: https://web.dust3d.org/
Support Chrome, Firefox, *Safari
*Safari, need enable Develop->Experiment Features->Allow WebGL in Web Workers.*
