### ISSUE TITLE
ability to import obj 

### ISSUE THREAD

**Issue by acheljay** [huxingyi/dust3d#52]
I try to import obj to try the software to use it in our photogrammetry workflow cause some options are very interesting in the post treatment but never found how to do it ... is it possible ?

**Comment by huxingyi** [comment]
Hi @acheljay currently, there is no option to import a mesh, but may add in the future to allow user import a mesh as a part. Thanks!

**Comment by acheljay** [comment]
Many thks could be great for some photogrammetry retouching

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
