### ISSUE TITLE
Raspbian failed to make

### ISSUE THREAD

**Issue by nigec** [huxingyi/dust3d#53]
I've been trying to build Dust3D with Raspbian OS but I seem to be missing some files
/usr/bin/ld: cannot find -linstant-meshes
/usr/bin/ld: cannot find -ltbb_static

I followed the tutorial from https://blogs.dust3d.org/2019/07/09/dust3d-on-raspberry-pi-3-model-b-plus/

**Comment by huxingyi** [comment]
Hi @nigec, there are a lot of changes since that blog been posted, the new changes haven't been tested on Raspberry Pi.
Please add `git checkout c73277a4aa` after the line `cd dust3d` to use the specified version:

https://github.com/huxingyi/dust3d/tree/c73277a4aa107dc4fce6eec565dfcb91d33c5ac4

**Comment by nigec** [comment]
hi @huxingyi 
That worked perfectly thank you 
Dust3D is up and running on Raspbian Debian GNU/Linux 10 (buster)

**Comment by huxingyi** [comment]
Thanks, glad to hear that, however, that version is quite outdated. Have you tried [Instant-Meshes](https://github.com/wjakob/instant-meshes) pre-combined binary before? Hopefully it will run on your machine, so then it should also work with the latest version of Dust3D with some changes to the compile command lines.

**Comment by nigec** [comment]
I installed Dust3D under Windows 10 but at 1920x1080 I was struggling with the font/icons sizes, so I thought I'd give Linux a try to see if it was any easier to see them and memorize the layout 
That was the method behind the madness lol
I'll have a look at Instant-Meshes

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
