### ISSUE TITLE
Possible glitch - unable to add to part without creating a new one

### ISSUE THREAD

**Issue by Papergami45** [huxingyi/dust3d#54]
With a node selected, switching to the add tool and clicking always creates a new part, without adding to my existing one. Can't find any fix or information on it.

**Comment by huxingyi** [comment]
Hi @Papergami45 The latest release no longer allow tree nodes branch. If you select the endpoints, you should be able to add new node. Try to overlap multiple parts instead.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
