### ISSUE TITLE
Feature Request: Support fbx/gltf2 import option

### ISSUE THREAD

**Issue by PravinKumar95** [huxingyi/dust3d#55]
It would be great to import gltf files into dust3d.

**Comment by huxingyi** [comment]
Hi, thanks for the suggestion, however, Dust3D is not a general purpose mesh editing software, it’s a mesh generator. The source document stores nodes info instead of vertex info.

**Comment by PravinKumar95** [comment]
Oh I see. Is there any way to use the auto uv unwrapper for my existing models?

**Comment by huxingyi** [comment]
There is no way for unwrapping an existing model which are not made in Dust3D, however, as you said, you can write your own application using simpleuv.
It's safe to leave facePartitions as empty. It can be used to pre split your mesh to groups. For example, you can assign your main body faces' partition as 1 and assign left limb faces' partition as 2. The group will be further split by face normal, so the front and back side will be in separate uv island.

**Comment by PravinKumar95** [comment]
Thanks for your reply. I will close this issue for now.
