### ISSUE TITLE
Feature Request: Command Line Interface / Benchmark?

### ISSUE THREAD

**Issue by michaellarabel** [huxingyi/dust3d#59]
Hi, nice program. I was wondering whether there are any plans to incorporate a command-line interface to the program or any official "benchmark" test for that matter? Mostly for evaluating the Dust3D performance on different CPUs/systems.

Thanks,
Michael

**Comment by huxingyi** [comment]
There are undocumented command line options to use for generating and exporting result without messing with GUI, please see here as example: https://github.com/huxingyi/dust3d/blob/fa3b07763494ff1defbb8528ccb08b4d642a5b52/appveyor.yml#L118

But it's not good for benchmark, currently, there is no official benchmark api, but you can get the rough time use from the debug window. Try to find something like this: 
> — DEBUG: The mesh generation took 348 milliseconds - src\meshgenerator.cpp:1591

You can open the same ds3 file on different CPUs/systems to compare.

Thanks!

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
