### ISSUE TITLE
Feature request: import from fbx or gltf

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#63]
I'm really frustrated with how slow it is to take models/animations from Blender and put them into Bablyon.js for a game, so I was really excited when I saw Dust3D since it looks a lot faster to use.

I'm using [Mixamo](https://www.mixamo.com/) to help with getting animations for characters in place, but getting one character from Blender into Mixamo and then from Mixamo back into Blender with all the animations is incredibly time consuming for what probably should be a one-line CLI command (merge *.fbx files with same skeleton/meshes but different animations into single animation -> export as gltf) 

I was hoping I could use Dust3D for this instead of Blender. I noticed you added an `Import` menu in the latest release:
![image](https://user-images.githubusercontent.com/709451/81903706-fd812400-9576-11ea-9cdd-9298b98ab1ec.png)

But its not clear to me what file format it imports, and it doesn't let me select either `obj` or `gltf`.

There are lots of libraries for dealing with `gltf` and `fbx` files, so if you were at some point to write a way to convert from your own format to one of those formats, it would probably be really easy to add support for all popular formats.

**Comment by huxingyi** [comment]
Currently support importing .ds3 format with mesh only. For example you can model the character’s head in a separate document and import to another document to composing the full body model.

Your suggestion is great, in the future, we may add supporting for fbx/glb importing. Currently, you can export as fbx or glb and combine the animations you downloaded in Unreal Engine or Unity.

**Comment by coosadog** [comment]
I downloaded it and installed it.  It looks nice but it's really useless to me since I can't import anything other than your own format.  You might as well get rid of the import option if you aren't going to use it.  Have you looked at assimp library!  It's good for importing and exporting many different formats.  You'd, of course, have to convert back and forth from/to yours.

**Comment by Hamu72** [comment]
Hi,
I think that it would help the popularity of this great program if it had a crossover with other programs. What I mean.
If it would be able to receive 3D meshes made in other programs in FBX or OBJ format. 
For example in ZBrush, Maya. Max, Blender, etc.

**Comment by buhatkj** [comment]
> I downloaded it and installed it. It looks nice but it's really useless to me since I can't import anything other than your own format. You might as well get rid of the import option if you aren't going to use it. Have you looked at assimp library! It's good for importing and exporting many different formats. You'd, of course, have to convert back and forth from/to yours.

same here.  A gltf or obj importer at least is necessary for this tool to be of any use for most folks.  I understand the issues with fbx, but some kind of importer is absolutely required.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
