### ISSUE TITLE
List of feedback for you

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#64]
Overall, I think Dust3D has a lot of potential. It's a lot easier to use than Blender and faster for simple things. I had some trouble making a person character with it, but I don't know how to do that in Blender either and I think I could do some simpler stuff like a table and some chairs.

I spent about an hour and a half playing with it, here's some stream-of-conscious feedback that I hope is helpful to you. 

Feel free to ignore all of it – this is unsolicited feedback and I am not a paying customer, so you have literally zero obligation to even reply to this and I'm happy you even just made this product to begin with

# Animations
![image](https://user-images.githubusercontent.com/709451/81914853-b00cb300-9586-11ea-80bd-c1211ef4b341.png)
- The circles for the bones are rather small. It would be great if I could zoom in.
- The mesh preview is small and it would be great if I could zoom in
- It would be great if I could play/pause the animation, like a video. It would make it much easier to see. Also, I would like to know if it can interpolate between frames? Its not clear without a play/pause button

Clicking [Change Reference Sheet] defaults to the hard disk folder, it would be better if it defaulted to the home directory:
![image](https://user-images.githubusercontent.com/709451/81915167-1691d100-9587-11ea-9cd9-6f4af9969702.png)

# Editor
- Can you make the tooltips here show up instantly on hover over an image? I didn't know what the icons represented at first and its helpful to not have to wait for the tooltip to appear 
![image](https://user-images.githubusercontent.com/709451/81915385-5ce73000-9587-11ea-8075-cc24fd711690.png)
- I suggest making the icons like 10px bigger, its pretty hard to see and I have 20/20 vision
- I initially expected clicking the zoom icon to zoom the entire canvas rather than change the button state to zoom, but it made sense after I tried it
- There's some unexpected behavior when you un-select the circle and then click Plus again. I expected it to associate the new node with the last created node, but instead it goes somewhere earlier.
- I didn't know you could re-position the mesh by holding  shift + middle click until it was mentioned in a video, I suggest some kind of visual indicator of controls for that. I found out by watching the linked YouTube video

I don't really know what green vs purple vs red means. 

![image](https://user-images.githubusercontent.com/709451/81916251-7046cb00-9588-11ea-8953-d6817bff1c4b.png)

I think red is X, green is Y, and I guess purple is Z? If so,  should those colors match up with the ones in the side here?
![image](https://user-images.githubusercontent.com/709451/81916289-7f2d7d80-9588-11ea-89ed-b9e0f8a8a72f.png)

# General
- It would be great if I could drag and drop to change the reference image. It would specifically. detect that I drag'n'drop'd a .png/jpg/image file

# Examples
- It would be great if the provided examples included poses & motion setup so I could base stuff of them
- If you had like 5 example humanoid characters (rather than animals/critters) it would be better I think.

On a larger project level, **it would be fantastic if you had a dynamic directory of user-generated content you could upload .ds3 files to from the editor**. That would save you a lot of work for creating high quality examples and YouTube videos. Especially if, as part of uploading it, the user agrees to license the assets freely – I'm sure Unity's asset catalog helped them get more users. You could even show how long it took the author to create the model, if you wanted to brag :). 

There are some fancy things you can do to make this easier - the backend could just be a bot that accepts files from the editor, and then uploads the files to this github repository, and the site could be statically built so it could be entirely hosted via github. That way, the cost of running that would be close to $0 or potentially $0.

**Comment by Jarred-Sumner** [comment]
Another thought: since Dust3D is based on nodes rather than triangles/vertices, how hard would it be to take something like [Bodypix](https://blog.tensorflow.org/2019/11/updated-bodypix-2.html) and automatically create meshes of people from them? You'd have the circles representing the points of the skeleton and probably the size as well.

If it worked, it'd be pretty cool. It wouldn't have to work 100% reliably either – even if it only _kind of_ worked as a starting point, it would be significantly better than tracing from scratch.

**Comment by Jarred-Sumner** [comment]
Followup suggestion: consider switching from the mailing list software you use to a Discord group.

It'd be much faster for people to help each other, and the mailing list software is pretty hard to use. It'd be an easy way to create more of a community around Dust3D.

**Comment by huxingyi** [comment]
Hi @Jarred-Sumner  All the suggestions are great, some of them I have been thinking about but haven't start to implement it yet, for example, allow user to upload to a directory.

> The circles for the bones are rather small. It would be great if I could zoom in.

You could maximize the animation window to make the circles bigger.

> The mesh preview is small and it would be great if I could zoom in

Indeed. TODO

> It would be great if I could play/pause the animation, like a video. It would make it much easier to see. Also, I would like to know if it can interpolate between frames? Its not clear without a play/pause button

Good idea. TODO

> Clicking [Change Reference Sheet] defaults to the hard disk folder, it would be better if it defaulted to the home directory:

TODO

> Can you make the tooltips here show up instantly on hover over an image? I didn't know what the icons represented at first and its helpful to not have to wait for the tooltip to appear

It's decided by Qt library. I guess it's not easy to change that.

> I suggest making the icons like 10px bigger, its pretty hard to see and I have 20/20 vision

TODO

> There's some unexpected behavior when you un-select the circle and then click Plus again. I expected it to associate the new node with the last created node, but instead it goes somewhere earlier.

If you select a single endpoint node, it should behave as what you say.

> I didn't know you could re-position the mesh by holding shift + middle click until it was mentioned in a video, I suggest some kind of visual indicator of controls for that. I found out by watching the linked YouTube video

TODO

> I don't really know what green vs purple vs red means.

The colored background of a node is the marker color.
The XYZ have different colors as you see from the tool bar, the X Y Z are icons for locking the movement of each axis. The last radius icon is for locking the radius. Red is front view(X), green is side view(Z)

> It would be great if I could drag and drop to change the reference image. It would specifically. detect that I drag'n'drop'd a .png/jpg/image file

TODO

BTW, We have a forum here: https://dust3d.discourse.group/

**Comment by alfredbaudisch** [comment]
Your suggestions and write up is very good, @Jarred-Sumner! 

I just disagree in regards to moving to Discord (Discord servers = mess for real productivite help). [Forum](https://dust3d.discourse.group/) + mailing list keep things in order and searcheable :)

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
