### ISSUE TITLE
Parts Tree icons almost invisible (also: acessibility and interface scaling for better readability)

### ISSUE THREAD

**Issue by alfredbaudisch** [huxingyi/dust3d#65]
System: Windows 10
Dust3D: 1.0.0-rc.6

1. Are the icons supposed to be faded-out with the background of the Parts Tree like this, being almost impossible to see? Not only that, but they are very small.
![dustIcons](https://user-images.githubusercontent.com/248383/81927733-6f438700-95e4-11ea-91b2-08d13f88a4fc.png)

2. My screen is 2560x1080, Dust3D interface in general is very small and hard to see. Any way to scale the icons, fonts, etc?
![dustIconstoolbar](https://user-images.githubusercontent.com/248383/81927735-6fdc1d80-95e4-11ea-96ce-fbefa67442b6.png)

**Comment by huxingyi** [comment]
Hi @alfredbaudisch Thanks for your reporting.

> Are the icons supposed to be faded-out with the background of the Parts Tree like this, being almost impossible to see? Not only that, but they are very small.

When it is not enabled, it supposed to be faded-out and being almost invisible. Yes, it's too small. 

> My screen is 2560x1080, Dust3D interface in general is very small and hard to see. Any way to scale the icons, fonts, etc?

Currently, there is no way to scale it. Normally, you don't need to click these toolbars, use hot keys.

Current UI is not good enough, we may refactor it after 1.0 stable version been released.

**Comment by alfredbaudisch** [comment]
Thanks for the quick answer, @huxingyi.

I'm a developer myself and I think I can help implementing some theming or UI customization (even although I never developed with Qt).

I tried compiling the code myself, but even following your guide, I still got linking errors, not matter what I tried (Win10). Did anything from [this document](https://docs.dust3d.org/en/latest/builds.html) change from the building process?

**Comment by huxingyi** [comment]
I am not sure, but the [ci file for Windows](https://github.com/huxingyi/dust3d/blob/master/appveyor.yml) should be always updated.

What are the build errors?

**Comment by alfredbaudisch** [comment]
It is failing when building CGAL-4.13 because of missing ZLib and other libs (which are not mentioned in the ci file). I tried getting zlib for Windows, but I couldn't manage to build zlib.lib and MSVCRT.lib, they only [provide a dll](http://gnuwin32.sourceforge.net/packages/zlib.htm). (_Btw, sorry if this one seems to basic, but in two decades of coding I never did C++ on Windows_).

```
"F:\AppData\Cpp\projects\dust3d\thirdparty\cgal\CGAL-4.13\build\ALL_BUILD.vcxproj" (destino padrão) (1) ->
"F:\AppData\Cpp\projects\dust3d\thirdparty\cgal\CGAL-4.13\build\src\CGAL_ImageIO\CGAL_ImageIO.vcxproj" (destino padrão)
 (5) ->
(Link destino) ->
  zlib.lib(gzlib.obj) : error LNK2019: sÝmbolo externo indefinido __imp__snprintf referenciado na funþÒo gz_error [F:\A
ppData\Cpp\projects\dust3d\thirdparty\cgal\CGAL-4.13\build\src\CGAL_ImageIO\CGAL_ImageIO.vcxproj]
  zlib.lib(gzwrite.obj) : error LNK2019: sÝmbolo externo indefinido __imp_vsnprintf referenciado na funþÒo gzvprintf [F
:\AppData\Cpp\projects\dust3d\thirdparty\cgal\CGAL-4.13\build\src\CGAL_ImageIO\CGAL_ImageIO.vcxproj]
  MSVCRT.lib(vsnprintf.obj) : error LNK2001: sÝmbolos externos indefinidos __imp_vsnprintf [F:\AppData\Cpp\projects\dus
t3d\thirdparty\cgal\CGAL-4.13\build\src\CGAL_ImageIO\CGAL_ImageIO.vcxproj]
  MSVCRT.lib(vsnprintf.obj) : error LNK2001: sÝmbolos externos indefinidos __imp__vsnprintf [F:\AppData\Cpp\projects\du
st3d\thirdparty\cgal\CGAL-4.13\build\src\CGAL_ImageIO\CGAL_ImageIO.vcxproj]
  F:\AppData\Cpp\projects\dust3d\thirdparty\cgal\CGAL-4.13\build\bin\Release\CGAL_ImageIO-vc140-mt-4.13.dll : fatal err
or LNK1120: 3 externo nÒo resolvidos [F:\AppData\Cpp\projects\dust3d\thirdparty\cgal\CGAL-4.13\build\src\CGAL_ImageIO\C
GAL_ImageIO.vcxproj]
```

**Comment by alfredbaudisch** [comment]
I tried:
```
.\vcpkg install zlib:x64-windows
.\vcpkg integrate install

# Then...
cmake -G "Visual Studio 15 2017" -A x64 ../ -DBOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0 -DCMAKE_TOOLCHAIN_FILE=C:/Libraries/vcpkg/scripts/buildsystems/vcpkg.cmake
msbuild /p:Configuration=Release ALL_BUILD.vcxproj
```

Still the same zlib linking errors.

**Comment by huxingyi** [comment]
That error message is weird. It report could not find __imp__snprintf. I guess is something related with your visual studio setup, but I am not sure. I would suggest, if the 64bit version not build, maybe you can try 32bit version to see if it works. Please check the CI file for the x86 platform.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
