### ISSUE TITLE
Add file association for .ds3 files by default

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#67]
When you click on a `.ds3` file in macOS, it shows this prompt:
![image](https://user-images.githubusercontent.com/709451/81973643-3d78f300-95d9-11ea-9de7-3c6739d6a72e.png)

It would be nice if it opened with Dust3D by default. I think this is a setting you can set when Dust3D is installed.

**Comment by huxingyi** [comment]
Good suggestion, I am not sure if we can connect file type with an unsigned app. I will do some research later.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
