### ISSUE TITLE
Add file extension when exporting if not already there

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#68]
When I enter a filename after clicking save, I expected it to automatically append .glb to the file, so it saved `camel` instead of `camel.glb`. It would be better if it detected that the filename is missing the extension, and appended it.

![image](https://user-images.githubusercontent.com/709451/81980790-196edf00-95e4-11ea-9b7d-0bb6c05c7970.png)

**Comment by huxingyi** [comment]
Good catch, this could be an easy fix. If someone want make a pull request, I am happy to merge it, or when I get a hand after finish the sculpting feature.

**Comment by huxingyi** [comment]
Thanks @Jarred-Sumner again for the catch and thanks @st4ll1 for the fix.
