### ISSUE TITLE
Increase max zoom of mesh preview

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#69]
I'd like to be able to zoom in on the mesh preview by about 200% more. This is the max it lets me.

![image](https://user-images.githubusercontent.com/709451/81982082-1543c100-95e6-11ea-89f6-7aa1946d9a62.png)

**Comment by huxingyi** [comment]
Thanks, indeed, this is an issue of the rc.6, it's already been fixed in rc.7
