### ISSUE TITLE
is there axial constraint when i draw joint?

### ISSUE THREAD

**Issue by xtvjxk123456** [huxingyi/dust3d#7]
is there axial constraint when I draw joint?

I think it is important for  the accuracy of shape

**Comment by xtvjxk123456** [comment]
just like Blender, move on single axis(x,y or z)

**Comment by huxingyi** [comment]
Good idea. But blender is kind of expert wise, for newbies like me, some feature looks not very obvious. Let's see how we can add constraint features.

**Comment by huxingyi** [comment]
Hi, I just thought about your suggestion, how about this? if the axis lock is on, the new node will be constrained on the same axis with the node it comes from.

**Comment by xtvjxk123456** [comment]
good idea.
what about collecting the opinions of others about this issues? There may be another better idea

**Comment by huxingyi** [comment]
Ok, so lets leave this issue open.

**Comment by huxingyi** [comment]
Hi, I am closing this now for the coming 1.0 version. Please feel free to open a new issue for the latest version.
