### ISSUE TITLE
Polish suggestions for macOS install

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#70]
On macOS, the convention for app filenames is for it to just be the app name. 

`Dust3D.app` rather than `dust3d-1.0.0-rc.6.app`:

![image](https://user-images.githubusercontent.com/709451/82085258-9318d280-96a1-11ea-8c9b-df8089b99059.png)

This is for a couple reasons:
- Its easier to search in Spotlight
- Most users won’t have multiple versions of the same app installed, so the version number is extra noise 

It doesn’t matter for the DMG file, just the .app

Additionally:
- It'd be nice if it included a link to the Applications folder in the DMG file, to make it easier to install
- it'd be extra nice if there was a high contrast background image, so that its a little easier to see when you have darkmode enabled

[This script](https://github.com/andreyvit/create-dmg) shows how to do the last two things

**Comment by huxingyi** [comment]
> Dust3D.app rather than dust3d-1.0.0-rc.6.app

Yes. TODO.

> It'd be nice if it included a link to the Applications folder in the DMG file, to make it easier to install

I guess this is the normal way of an installer on MacOS, and we should follow it, thanks. TODO.

**Comment by Calinou** [comment]
> it'd be extra nice if there was a high contrast background image, so that its a little easier to see when you have darkmode enabled

A white outline could be added to the icon to make it visible in any background. This way, it'd also be visible when docked if you use a dark background.

**Comment by huxingyi** [comment]
Good idea. Need to do it before the 1.0 stable version been released.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
