### ISSUE TITLE
Two different selection types in side panel is confusing

### ISSUE THREAD

**Issue by Jarred-Sumner** [huxingyi/dust3d#74]
I keep thinking the orange border in the side panel means that the hovered circle belongs to that body part, when its actually the one with the yellow opacity

I suggest making it a single selection state, and making it so that whatever circle I click, it highlights that one and only that one in the side panel.

![image](https://user-images.githubusercontent.com/709451/82625581-67fb1b00-9b9a-11ea-8a8a-8fc5e37b1f9f.png)

As a side note, I'm really confused how the antlers work in the backpacker example because I only see two circles and moving them seems to rotate the antlers.

Is that a separate file entirely that is imported?

**Comment by huxingyi** [comment]
Yes, it’s confusing, but the two different selections are not the same, I don’t know how to unify the UI yet.

You are right, the antlers is imported as a separate document, although there is no UI indication about the importing.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
