### ISSUE TITLE
How is cut-face supposed to work

### ISSUE THREAD

**Issue by tex** [huxingyi/dust3d#77]
Whatever I do I am unable to make it work. I saw demo with chair, but it is too fast, and I am unable to reproduce it.
Can you check that it still works? I am trying latest release (rc-6).
Thanks!

**Comment by huxingyi** [comment]
[chair.zip](https://github.com/huxingyi/dust3d/files/4842182/chair.zip)
Hi, I just checked the windows 64 version, it works. What's your operating system please? You can try this file, please unzip the chair.ds3 and open it in Dust3D.

**Comment by tex** [comment]
Opened chair.zip and got this on Linux:

![s1](https://user-images.githubusercontent.com/27386/85950414-d16e0680-b95c-11ea-8cf1-ead39e92bc0a.png)

**Comment by tex** [comment]
But I am looking for some more detailed how to use it. More precisely how to model flat surface.

**Comment by tex** [comment]
Oh, I figured it out. But the example chair is rendered as is shown on the screenshot.

**Comment by huxingyi** [comment]
![image](https://user-images.githubusercontent.com/3941597/85958860-f9e71680-b9d7-11ea-9854-842b5de03505.png)
You can adjust the rotation to fix it. If you haven't made any change to the chair model and it shows as this, I guess there are inconsistance of the algorithm between windows and linux.
