### ISSUE TITLE
AppImage symbol lookup error on CentOS8

### ISSUE THREAD

**Issue by marcomeyerVFX** [huxingyi/dust3d#78]
Getting this error when running the appimage:

`dust3d: symbol lookup error: /lib64/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n`

dust3d-1.0.0-rc.6

**Comment by huxingyi** [comment]
Thanks for reporting, AppImage build for Dust3D doesn't support CentOS yet, you can try to install from [flathub](https://flathub.org/apps/details/org.dust3d.dust3d), during the installing, it may stuck on 0% for minutes, just wait and it will finish.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
