### ISSUE TITLE
Opening on a HiDPI monitor causes model to be rendered tiny.  

### ISSUE THREAD

**Issue by henrytseng** [huxingyi/dust3d#79]
Running on archlinux with XPS 13 with HiDPI monitor - high density monitor.

**Comment by huxingyi** [comment]
Thanks for reporting, could you show me a screenshot let me see how bad it is :-)
Anyway, the UI will be refactored in next release.

**Comment by Calinou** [comment]
This is probably a duplicate of https://github.com/huxingyi/dust3d/issues/40.

**Comment by henrytseng** [comment]
Sure.  I'll close this issue and add to #40
