### ISSUE TITLE
Not enough contrast between icons and interface

### ISSUE THREAD

**Issue by hellocatfood** [huxingyi/dust3d#82]
I'm using Dust3D 1 rc6 on Ubuntu 20.04 and I think there's isn't enough contrast in the icons in the parts toolbar and the interface.

![Screenshot from 2020-07-31 19-39-08](https://user-images.githubusercontent.com/151947/89072572-beda5900-d370-11ea-9a69-84211ff68251.png)

They're also a bit too small but I see someone else has raised that issue. For reference here's the GIMP icons which have much better contrast (the interface is also less dark).

![Screenshot from 2020-07-31 19-39-27](https://user-images.githubusercontent.com/151947/89072679-edf0ca80-d370-11ea-863f-ee492e4e640e.png)

**Comment by hellocatfood** [comment]
Agreed that it should be grey out when not selected/turned on but the contrast isn't high enough ad they kinda blend into the interface

**Comment by huxingyi** [comment]
I got you, the contrast should be increased.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
