### ISSUE TITLE
Changing node radius with touchpad

### ISSUE THREAD

**Issue by bobpepin** [huxingyi/dust3d#83]
I am using Dust3D on a Macbook Air with the built-in touchpad, where Qt maps "mouse scroll" to a two-finger swipe up/swipe down. The radius of nodes is very hard to control, since Qt usually ends up sending an extra mouse scroll event when lifting the fingers from the touchpad, changing the radius. Qt also seems to send mouse scroll events with quite big increments for small finger movement, so the whole experience is really jumpy. In practice that means that I have to move two fingers really slowly and when the radius is right, try to click with both fingers without moving too much so that it shows the menu and stops sending mouse scroll events, and then I can lift the fingers.
Would be be possible to have an option for changing the radius for example using mouse movement plus a modifier key like shift, control, option, ...?

**Comment by huxingyi** [comment]
Thanks for the suggestion. Will looking into it.

**Comment by bobpepin** [comment]
Ideally we might want to have some kind of "handle" to drag for resizing, that most closely resembles how one would resize things in gimp or powerpoint for example. That would not be an option for node resizing during node placement, however, unless we do click-and-drag for placement plus radius selection. Not sure how intuitive that would be.
As an extra it would be nice to be able to numerically enter a node radius, if one wants to make sure that certain nodes have the same radius.

**Comment by bobpepin** [comment]
I just had a look at how Gimp does bezier curves, which are also center + radius/direction, they use click-and-hold when placing plus handles for adjusting, seems to work well.

**Comment by huxingyi** [comment]
Thanks for the research, we should follow the common practices. The extra UI element such as handles are not trivial to implement though.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
