### ISSUE TITLE
Node circles hard to see

### ISSUE THREAD

**Issue by bobpepin** [huxingyi/dust3d#85]
On my Macbook Air with built-in screen, the green and orange node circles can be really hard to see when having the display on medium brightness. I am also thinking red vs. green is maybe not ideal for color-blind people.
Maybe it helps to increase the line width?

**Comment by huxingyi** [comment]
The UI is hard, currently, there are many places useing red and green to indicate states. Change that is not easy.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
