### ISSUE TITLE
Feature request: orange pen/green pen

### ISSUE THREAD

**Issue by bobpepin** [huxingyi/dust3d#86]
Sometimes it could be convenient to place nodes directly in the top-view (green circles), is there already such a feature? If not, I would suggest having two different "+" options, one orange and one green that adds nodes in the respective axis.

**Comment by huxingyi** [comment]
Good idea, but two icons may confuse new users, maybe a preferece setting to let user choose, or use the screen coord (which side) to decide.

**Comment by bobpepin** [comment]
Screen coords sounds good, that was actually also the first thing I tried. This would imply a "hard" split between left and right screen half, but I don't think that would be a problem in practice.

**Comment by hikari-no-yume** [comment]
You can press the “A” key to add a node, so maybe some modifier like Shift+A could be for adding for the other side.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
