### ISSUE TITLE
Compilation errors on MacOS

### ISSUE THREAD

**Issue by bobpepin** [huxingyi/dust3d#87]
I had to make the following changes to compile on macos with the latest Qt and CGAL installed by brew.

1. Some parts of boost have `#include <version>`, due to case-insensitivity of APFS this resolves to thirdparty/quickjs/quickjs-2019-07-09-dust3d/VERSION which is not a header file. Renaming the latter file helped, switching around the order of the include paths in dust3d.pro so that boost comes before quickjs probably also works.

2. The CGAL installed by brew requires C++14. Inserting "CONFIG += c++14" in the macos {} section of the .pro file did the trick.

3. The CGAL seems to be template-only, I got it to compile the brute-force way by removing -lcgal from the generated Makefile. Removing the corresponding entry from the .pro file probably also does the trick (CGAL_LIBNAME?).

Sorry for not testing out the "proper" solutions, but it takes quite a long time to compile on my MacBook.

**Comment by huxingyi** [comment]
Current .pro file and related CI files have a lot hacks to make it work. Your observation is invaluble, thanks, especially since I have switched my main development environment from a Mac Book to a Dell Windows.

**Comment by bobpepin** [comment]
I just tried swapping around the order of include paths for point 1, doesn't work.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
