### ISSUE TITLE
Blank white screen on Windows 7 64-bit

### ISSUE THREAD

**Issue by Monster-Gaming-Studios** [huxingyi/dust3d#89]
My issue is same as #9. I am getting blank white screen, but the menus are working fine(sorry I could not take a screenshot of  the menus). If I click where all the menus are supposed to be, I get the menus, but everything else is blank. I tried the fix you told in issue #9, but that does not work.

The problem might be with my laptop being too old; it only supports OpenGl  2.1 completely and 3.1 partially. My graphics driver is also too old. It is Mobile Intel(R) 4 Series Express Chipset Family (Core Profile 2.0). But, it would be great if you can do something about it. I am able to run Blender 2.7 without any problem and 2.8 with emulation.

Attachment:-

![Dust3d](https://user-images.githubusercontent.com/55491103/90329946-b582fa80-dfc6-11ea-8aa8-6431e30da5fc.JPG)

**Comment by huxingyi** [comment]
Could you try this to see if it works please ?

Open a windows command line, 
```
> cd dust3d-1.0.0-rc.6
> set QT_OPENGL=software
> dust3d.exe
```

**Comment by Monster-Gaming-Studios** [comment]
That works. Tanks for your quick response. I made a batch file to automate the variable setting and every time I want to use Dust3D, I launch the batch file instead of the main executable. Thank you.
