### ISSUE TITLE
While compiling dust3d, I got an error.

### ISSUE THREAD

**Issue by Jonas-Salcedo** [huxingyi/dust3d#92]
While attempting to compile dust3d, I got this error
make: *** [Makefile:3462: obj/modeloffscreenrender.o] Error 1
while following this tutorial 

;Install Qt5
$ sudo apt-get install --reinstall qtchooser
$ sudo apt-get install qtbase5-dev

;Prepare compile environment for CGAL-4.13
$ sudo apt-get install libcgal-dev  ; This is not the latest version, will encounter compiler error when build the Dust3D with this version, but helps resolve internal dependencies of CGAL for you
$ sudo apt install cmake

;Install CGAL-4.13
$ wget https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.13/CGAL-4.13.zip
$ unzip CGAL-4.13.zip
$ cd CGAL-4.13
$ mkdir build
$ cd build
$ cmake ../
$ make
$ sudo make install

;Clone the Main project
$ cd ~/Documents
$ git clone https://github.com/huxingyi/dust3d.git

;Compile Dust3D
$ cd ~/Documents/dust3d
$ qmake -qt=5 -makefile
$ make
$ ./dust3d

I tried installing CGAL 5.1, but that does not seem to work. Can anyone help? I am compiling for Raspberry Pi 4 8gb. I don't think there are any issues with the ARM architecture as most of the components seem to be compatible with ARM.

**Comment by huxingyi** [comment]
Hi, the latest version havn't been tested on Rsapberry Pi yet, please check https://github.com/huxingyi/dust3d/issues/53 for reference.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
