### ISSUE TITLE
Zoom out button do not work on default sized canvas

### ISSUE THREAD

**Issue by MekBoss** [huxingyi/dust3d#93]
"Zoom out" option do not work if trying to apply it on canvas with "default" resolution.

At the "backpacker" example, I cant see part of a head model.
![HRODA6A4 — копия — копия (3)](https://user-images.githubusercontent.com/43208093/95740654-9a1a3000-0c95-11eb-8389-ce6a89f870ee.png)

It kinda work if you apply "zoom in" option for once and then "zoom out", but future "zoom out" reset resolution to default.
Cant say more since I tight on disk space and cant install Qt to debug it.

**Comment by huxingyi** [comment]
"Zoom out" option is designed as that, maybe need change in next release.

The backpacker example is special, that head is an imported document, so there is nothing else but two nodes as placeholder.

**Comment by huxingyi** [comment]
Hi @MekBoss thanks again, the zoom out is been fixed.

**Comment by MekBoss** [comment]
Much appreciated :-*
