### ISSUE TITLE
Possibility to rotate single-node part

### ISSUE THREAD

**Issue by hikari-no-yume** [huxingyi/dust3d#96]
I am aware that you can orient a part by forming a chain of nodes pointing in a particular direction. For example:

![two linked nodes, one above the other, produces a long cuboid facing up](https://user-images.githubusercontent.com/579774/97218819-7a245980-17c9-11eb-9f80-fd13a8f00c73.png) ![two linked nodes, one to the right of the other, produces a long cuboid facing to the side](https://user-images.githubusercontent.com/579774/97218885-91fbdd80-17c9-11eb-95e3-3de0c7984cab.png)

However, so far as I can tell you cannot orient a part that is just a single node.

For a cuboid-like shape this can be fine, it looks essentially the same regardless of whether it is one node or two:

![single-node part forming a cube](https://user-images.githubusercontent.com/579774/97219157-e30bd180-17c9-11eb-9420-dbae2c31d6c1.png), ![two-node part forming a cube](https://user-images.githubusercontent.com/579774/97219203-f454de00-17c9-11eb-872c-2547280d2938.png)

So for that case it might not be a problem.

However, for a part using the Subdivide modifier, they look quite different:

![single-node part with Subdivide forming a sphere](https://user-images.githubusercontent.com/579774/97219394-3da52d80-17ca-11eb-8147-03623d6923e6.png) ![two-node part with Subdivide forming a cylinder](https://user-images.githubusercontent.com/579774/97219335-26664000-17ca-11eb-8bb5-e401bce8c26a.png)

A sphere looks almost the same from every direction so it does not matter too much for that case.

But combining the Subdivide and Deform modifiers can get nice shapes like this:

![single-node part with Subdivide and Deform forming an oblate spheroid](https://user-images.githubusercontent.com/579774/97219689-9f659780-17ca-11eb-9b4e-238c7d8df0db.png) (Thickness: 0.2, Width: 0.2)

I think they are called “oblate spheroids”. They have a clear orientation, unlike a normal sphere. So it would be useful to be able to rotate them somehow. Of course I can change the radius of the node and the Thickness and Width parameters to achieve an 90° rotation on some axis, but what I am interested in is achieving other rotations.

The original thing I wanted to use this for was legs of a human body. They are not perfectly straight, so if I form a leg out of three or more of these, I would like to have the upper leg and lower leg at different angles. (For topology reasons it might not actually be a good idea to use this shape for legs, but there must be other uses too.) 

I apologise if there is already a way to achieve this that I have missed! I am aware there is some posing/rigging feature but right now it is the base model I am interested in.

**Comment by hikari-no-yume** [comment]
By the way, you do not need to prioritise this, I am sure I can find other ways to do things. It just would be nice to have.

**Comment by huxingyi** [comment]
Agree, there are slight differences between single node and multiple nodes part need to be fixed.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
