### ISSUE TITLE
When I execute the executable, the program opens, but I just get a black screen.

### ISSUE THREAD

**Issue by PhlegethonAcheron** [huxingyi/dust3d#98]
I downloaded the windows x64 build, followed all the installation instructions, and opened the program, to just see a black box with  a titlebar. I can tell that there is a bar at the top that doesn't stretch the whole width of the window, and there is a resizable portion somewhere, but, other than blindly exploring what I believe to be tabs, I can't figure much else out.
I can see the drop-down menus that probably come from some sort of tabs, and I can access the right-click menu, but beyond that, there isn't much else that I can do.
![image](https://user-images.githubusercontent.com/53194290/98403136-7a78ec00-2036-11eb-9616-8c095023898f.png)
I also tried rc5, and the problem still exists there as well.

**Comment by huxingyi** [comment]
Hi, could you try this to see if it works: https://github.com/huxingyi/dust3d/issues/89

**Comment by PhlegethonAcheron** [comment]
it worked, thank you! I'll do what the other person did and make a bat file to open the program.
