### ISSUE TITLE
Wrong filename in documentsaver.cpp

### ISSUE THREAD

**Issue by KaruroChori** [huxingyi/dust3d#99]
The file **objectXml.h** is included, however the actual name is objectxml.h.
Compilation fails on unix based systems bacause of this.

**Comment by luzpaz** [comment]
Can't find this file in the source code.

**Comment by luzpaz** [comment]
Looks like related to #113

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
